name: Look at her
favicon: null
layout_spectrum: 0.5376688411924988
typography_spectrum: 0.14032516162842512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1143623876851052
  lightness: 0.7576751089654863
  saturation: 0.639670261181891
  rhythmicContrast: 0.3448942059185356
purpose: []
